#!/usr/bin/env python3
"""Generate native foundation tokens; --check detects stale generated files."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
p = argparse.ArgumentParser()
p.add_argument('--check', action='store_true')
args = p.parse_args()
spec = json.loads((ROOT / 'design-system/tokens.json').read_text())
swift = ['// Generated by scripts/design-tokens.py. Edit design-system/tokens.json.', 'import CoreGraphics', '', 'enum PebbleTokens {']
kotlin = ['// Generated by scripts/design-tokens.py. Edit design-system/tokens.json.', 'package dev.leafnotes', '', 'object PebbleTokens {']
for name, token in spec['tokens'].items():
    value = token['value']
    if token['type'] == 'integer':
        assert isinstance(value, int) and value >= 0, name
        swift.append(f'    static let {name}: Int = {value}')
        kotlin.append(f'    const val {name}: Int = {value}')
    else:
        assert isinstance(value, (int, float)) and value >= 0, name
        swift.append(f'    static let {name}: Double = {float(value)}')
        kotlin.append(f'    const val {name}: Float = {float(value)}f')
swift.append('}')
kotlin.append('}')
outputs = {'mac/Sources/PebbleTokens.swift': swift, 'android/app/src/main/java/dev/leafnotes/PebbleTokens.kt': kotlin}
for path, lines in outputs.items():
    target = ROOT / path
    content = '\n'.join(lines) + '\n'
    if args.check:
        if not target.exists() or target.read_text() != content:
            raise SystemExit(f'Stale tokens: {path}; run python3 scripts/design-tokens.py')
    else:
        target.write_text(content)
print('Pebble foundation tokens are current.' if args.check else 'Generated Swift and Kotlin foundation tokens.')
