import SwiftUI
import AppKit
import LinkPresentation

struct ClipboardItem: Identifiable {
    var id = UUID(); var text = ""; var image: NSImage?; var files: [URL] = []; var link: URL?
    var title: String { image != nil || !files.isEmpty ? "Copied image" : link != nil ? "Copied link" : "Copied text" }
}
@MainActor final class ClipboardCapture: ObservableObject {
    static let shared = ClipboardCapture()
    @Published var item: ClipboardItem?
    @Published var linkTitle = ""
    @Published var thumbnail: NSImage?
    private var seen = -1
    private var monitor: Any?
    private var provider: LPMetadataProvider?
    private weak var store: NoteStore?
    private var windows: [ObjectIdentifier: ClipboardWindowStore] = [:]
    var activeStore: NoteStore? { guard let window = NSApp?.keyWindow else { return nil }; return windows[ObjectIdentifier(window)]?.store }
    func register(_ store: NoteStore, window: NSWindow) { windows = windows.filter { $0.value.window != nil && $0.value.store != nil }; windows[ObjectIdentifier(window)] = ClipboardWindowStore(window, store) }
    func start(_ store: NoteStore) {
        self.store = store
        if monitor == nil { monitor = NSEvent.addLocalMonitorForEvents(matching: .keyDown) { [weak self] event in
            let handled = MainActor.assumeIsolated {
                guard let self, event.modifierFlags.intersection(.deviceIndependentFlagsMask) == .command, event.charactersIgnoringModifiers?.lowercased() == "v", let active = self.activeStore, active.selected == nil, !(NSApp.keyWindow?.firstResponder is NSTextView) else { return false }
                guard let candidate = Self.read() else { return false }; self.save(candidate); return true
            }
            return handled ? nil : event
        } }
        inspect()
    }
    static func read(_ board: NSPasteboard = .general) -> ClipboardItem? {
        let privateTypes = ["org.nspasteboard.ConcealedType", "org.nspasteboard.TransientType", "org.nspasteboard.AutoGeneratedType"]
        guard !(board.types ?? []).contains(where: { privateTypes.contains($0.rawValue) }) else { return nil }
        let files = (board.readObjects(forClasses: [NSURL.self], options: nil) as? [URL] ?? []).filter { $0.isFileURL }
        // Read actual bitmap bytes only. NSImage(pasteboard:) also opens file URLs,
        // which can block forever on a stale cloud/file-provider URL.
        for type in [NSPasteboard.PasteboardType.png, .tiff] { if let data = board.data(forType: type), data.count <= 40_000_000, let image = NSImage(data: data) { return ClipboardItem(image: image, files: files) } }
        if !files.isEmpty { return ClipboardItem(files: files) }
        let text = (board.string(forType: .string) ?? board.string(forType: .URL) ?? "").trimmingCharacters(in: .whitespacesAndNewlines)
        guard !text.isEmpty, text.utf8.count <= 2_000_000 else { return nil }
        let url = URL(string: text).flatMap { ["http","https"].contains($0.scheme?.lowercased() ?? "") && $0.host != nil ? $0 : nil }
        return ClipboardItem(text: text, link: url)
    }
    func inspect() {
        guard UserDefaults.standard.object(forKey: "clipboardSuggestions") as? Bool != false else { dismiss(); return }
        guard NSPasteboard.general.changeCount != seen else { return }; seen = NSPasteboard.general.changeCount
        provider?.cancel(); item = Self.read(); thumbnail = item?.image; linkTitle = ""
        if let value = item { Task { try? await Task.sleep(for: .seconds(5)); if self.item?.id == value.id { self.dismiss() } } }
        guard let value = item, let url = value.link else { return }
        let request = LPMetadataProvider(); request.timeout = 8; provider = request
        request.startFetchingMetadata(for: url) { [weak self] metadata, _ in
            Task { @MainActor in
                guard let self, self.item?.id == value.id else { return }; self.linkTitle = metadata?.title ?? ""
                metadata?.imageProvider?.loadObject(ofClass: NSImage.self) { [weak self] image, _ in
                    Task { @MainActor in if self?.item?.id == value.id { self?.thumbnail = image as? NSImage } }
                }
            }
        }
    }
    func dismiss() { provider?.cancel(); item = nil; thumbnail = nil; linkTitle = "" }
    func save(_ candidate: ClipboardItem? = nil, into target: NoteStore? = nil) {
        guard let value = candidate ?? item, let store = target ?? activeStore ?? store else { return }
        let title = value.link != nil && item?.id == value.id ? linkTitle : ""
        store.create(); guard store.current != nil else { return }
        if let image = value.image, let data = image.tiffRepresentation, let rep = NSBitmapImageRep(data: data), let png = rep.representation(using: .png, properties: [:]) {
            let file = FileManager.default.temporaryDirectory.appendingPathComponent("Copied image-\(UUID().uuidString).png")
            do { try png.write(to: file); store.importFiles([file]); try? FileManager.default.removeItem(at: file); store.update { $0.title = "Copied image" } } catch { store.error = error.localizedDescription }
        } else if !value.files.isEmpty {
            store.importFiles(value.files)
        } else {
            store.update { note in
                note.title = !title.isEmpty ? title : value.link?.host ?? String(value.text.components(separatedBy: .newlines).first?.prefix(70) ?? "")
                note.text = value.text
                if value.link != nil { note.spans = [TextSpan(start: 0, length: value.text.utf16.count, kind: "link:" + value.text)] }
            }
        }
        store.flush(); dismiss()
    }
}
struct ClipboardToast: View {
    @ObservedObject var capture: ClipboardCapture
    var body: some View {
        if let item = capture.item {
            HStack(spacing: 10) {
                if let image = capture.thumbnail { Image(nsImage: image).resizable().scaledToFill().frame(width: 40, height: 40).clipShape(RoundedRectangle(cornerRadius: 9)) }
                else { Image(systemName: "clipboard").font(.system(size: 20)).foregroundStyle(.secondary).frame(width: 32) }
                VStack(alignment: .leading, spacing: 3) {
                    Text(capture.linkTitle.isEmpty ? item.title : capture.linkTitle).font(.system(size: 13, weight: .medium)).lineLimit(1)
                    if item.image == nil && !item.text.isEmpty { Text(item.text).font(.system(size: 12)).foregroundStyle(.secondary).lineLimit(1) }
                }.frame(maxWidth: .infinity, alignment: .leading)
                Button { capture.save() } label: { Label("Save", systemImage: "plus").padding(.horizontal, 12).frame(height: 36).background(Color.primary.opacity(0.07), in: Capsule()).contentShape(Capsule()) }.buttonStyle(.plain)
                GlassIcon(icon: "xmark", label: "Dismiss clipboard suggestion") { capture.dismiss() }
            }.padding(12).frame(width: 340).background(.regularMaterial, in: RoundedRectangle(cornerRadius: 18)).overlay(RoundedRectangle(cornerRadius: 18).strokeBorder(Color.primary.opacity(0.08))).shadow(color: .black.opacity(0.15), radius: 18, y: 8).padding(20)
        }
    }
}

@MainActor final class ClipboardWindowStore {
    weak var window: NSWindow?; weak var store: NoteStore?
    init(_ window: NSWindow, _ store: NoteStore) { self.window = window; self.store = store }
}
struct ClipboardWindowRegistration: NSViewRepresentable {
    var store: NoteStore
    func makeNSView(context: Context) -> ClipboardRegistrationView { let view = ClipboardRegistrationView(); view.store = store; return view }
    func updateNSView(_ view: ClipboardRegistrationView, context: Context) { view.store = store; if let window = view.window { ClipboardCapture.shared.register(store, window: window) } }
}
class ClipboardRegistrationView: NSView {
    weak var store: NoteStore?
    override func viewDidMoveToWindow() { super.viewDidMoveToWindow(); if let window, let store { ClipboardCapture.shared.register(store, window: window) } }
}
